name: "Build and deploy Typescript Site"
author: "Paul Koos"
description: "This will compile typescript with the tsc command."
inputs:
  deploy-branch:
    description: "The name of the branch being used to deploy to GitHub Pages"
    required: true
  tsc-directory:
    description: "Where the tsconfig.json file is located within the project. If this is left out, the default project folder is used instead."
    required: false
runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'heart'
  color: 'red'
